# Generated by Django 4.1.7 on 2023-04-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('comision', models.IntegerField()),
                ('codigo', models.CharField(max_length=10)),
                ('imagen', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=50)),
                ('cursos', models.ManyToManyField(to='AppColegio.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_entrega', models.DateField()),
                ('entregado', models.BooleanField()),
                ('estudiante', models.ForeignKey(null='Desconocido', on_delete=django.db.models.deletion.CASCADE, to='AppColegio.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiante',
            field=models.ForeignKey(null='Desconocido', on_delete=django.db.models.deletion.CASCADE, to='AppColegio.estudiante'),
        ),
    ]
