# Generated by Django 4.1.7 on 2023-04-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppColegio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='entregable',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiante',
            field=models.ManyToManyField(to='AppColegio.estudiante'),
        ),
        migrations.AddField(
            model_name='entregable',
            name='estudiante',
            field=models.ManyToManyField(to='AppColegio.estudiante'),
        ),
    ]
